# \uB85C\uADF8 \uD30C\uC77C \uACBD\uB85C \uC124\uC815
log.folder.path=/home/nhnacademy/Documents/1129/logs


# InfluxDB \uC5F0\uACB0 \uC815\uBCF4
influxdb.url=http://localhost:8086
influxdb.token=hSR0rgdLbf3CX0eusGykfx6SjxpFuM2UhneYBdIkY8xIN6k-eX2P8XdN2Tlt0BXo6ANETkZdF1WT30fMh7EiKg==
influxdb.org=javame
influxdb.bucket=test